SELECT
    COUNT(*) AS FISH_COUNT
FROM
    FISH_INFO
WHERE
    FISH_TYPE IN
    (SELECT
        FISH_TYPE
    FROM
        FISH_NAME_INFO
    WHERE
        FISH_NAME IN ('BASS', 'SNAPPER')
    );

# 이건 왜 안돼요?
# SELECT
#     COUNT(I.ID) AS FISH_COUNT
# FROM
#     FISH_INFO AS I
#     JOIN FISH_NAME_INFO AS N USING (FISH_TYPE)
# WHERE
#     N.FISH_NAME IN ('BASS', 'SNAPPER')