SELECT
    DISTINCT(CAR_ID) AS CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    USING (CAR_ID)
WHERE
    CAR_TYPE = '세단'
    AND LEFT(START_DATE,7) = '2022-10'
ORDER BY
    1 DESC;