SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(S.USER_ID) AS USERS
FROM
    USER_INFO I
    JOIN ONLINE_SALE S
    USING (USER_ID)
WHERE
    GENDER IS NOT NULL
GROUP BY
    YEAR,
    MONTH,
    GENDER
ORDER BY
    1,
    2,
    3;