SELECT
    CASE
        WHEN GROUP_CONCAT(NAME) LIKE ("%Python%") AND GROUP_CONCAT(CATEGORY) LIKE("%Front%") THEN "A"
        WHEN GROUP_CONCAT(NAME) LIKE ("%C#%") THEN "B"
        WHEN GROUP_CONCAT(CATEGORY) LIKE ("%Front%") THEN "C"
        END AS  GRADE,
    ID,
    EMAIL
FROM
    SKILLCODES S
    JOIN DEVELOPERS D
    ON (SKILL_CODE & CODE = CODE)
GROUP BY
    ID,
    EMAIL 
HAVING
    GRADE IS NOT NULL
ORDER BY
    1,
    2;