WITH
    RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23)
SELECT
    H.HOUR,
    COUNT(ANIMAL_ID) AS COUNT
FROM
    HOURS H
    LEFT JOIN ANIMAL_OUTS O
    ON H.HOUR = HOUR(O.DATETIME)
GROUP BY
    H.HOUR
ORDER BY
    1;
# COUNT(*)로 하면 0인 시간도 1로 카운트됨...?

# 데이터가 없는 시간은 제외됨.
# SELECT
#     DISTINCT(HOUR(DATETIME)) AS HOUR,
#     COUNT(*) AS COUNT
# FROM
#     ANIMAL_OUTS
# GROUP BY
#     HOUR(DATETIME)
# ORDER BY
#     1;