WITH RENT AS (
SELECT
    HISTORY_ID,
    H.CAR_ID,
    CAR_TYPE,
    DAILY_FEE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS DAY,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    ELSE '7일 미만' END AS DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    USING (CAR_ID)
WHERE
    CAR_TYPE = '트럭'
)

SELECT
    HISTORY_ID,
    FLOOR(((100 -  IFNULL(DISCOUNT_RATE, 0)) / 100) * DAILY_FEE * DAY) AS FEE
FROM
    RENT R
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON R.CAR_TYPE = P.CAR_TYPE AND R.DURATION = P.DURATION_TYPE
ORDER BY
    2 DESC,
    1 DESC;
    
# 왜 안될까...?
# WITH RENT AS (
# SELECT
#     HISTORY_ID,
#     H.CAR_ID,
#     CAR_TYPE,
#     DAILY_FEE,
#     DATEDIFF(END_DATE, START_DATE) + 1 AS DAY,
#     CASE
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
#         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
#     END AS DURATION_TYPE
# FROM
#     CAR_RENTAL_COMPANY_CAR C
#     JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
#     USING (CAR_ID)
# WHERE
#         CAR_TYPE = '트럭'
# )
# SELECT
#     HISTORY_ID,
#     FLOOR((1 - (IFNULL(DISCOUNT_RATE, 0) / 100)) * DAILY_FEE * DAY) AS FEE
# FROM
#     RENT R
#     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
#     ON R.CAR_TYPE = P.CAR_TYPE
#     AND R.DURATION_TYPE = P.DURATION_TYPE
# ORDER BY
#     2 DESC,
#     1 DESC;