SELECT
    B.BOOK_ID,
    A.AUTHOR_NAME,
    LEFT(B.PUBLISHED_DATE,10) AS 'PUBLISHED_DATE'
FROM
    BOOK AS B
    JOIN AUTHOR AS A USING (AUTHOR_ID)
WHERE
    B.CATEGORY LIKE '%경제%'
ORDER BY
    B.PUBLISHED_DATE;